name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  compose:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "../docker-compose.yml"
          # up-flags: "--build"
          down-flags: "--volumes"
          test-container: "app"
          test-command: "npm test"