name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  compose:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.ci.yml"
          # up-flags: "--build"
          down-flags: "--volumes"
          test-container: "app"
          test-command: "npm test"
          annotate: false
        env:
          MYSQLDB_USER: "root"
          MYSQLDB_ROOT_PASSWORD: "123456"
          MYSQLDB_DATABASE: "flowpay_router_db"
          MYSQLDB_LOCAL_PORT: "3306"
          MYSQLDB_LOCAL_TEST_PORT: "3307"
          MYSQLDB_DOCKER_PORT: "3306"

          NODE_LOCAL_PORT: "3000"
          NODE_DOCKER_PORT: "3000"